1. Выполнить предобработку текстов выбранного писателя. Инструментарий предобработки оформить в виде метода.
2. Посчитать косинусное сходство текстов. Оформить также в виде метода. Допустимые библиотеки: numpy и sklearn.

In [ ]:
%pip install -U pymorphy3-dicts-ru

In [35]:
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
import pymorphy3
import nltk
import codecs
import os

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
nltk.download('punkt')
stop = stopwords.words("russian")
morph = pymorphy3.MorphAnalyzer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\1\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [37]:
# class text():

# def optokfil(filename):
#         with codecs.open(filename, "r", "utf-8") as my_file:
#             text = my_file.read().lower()
#         tokenized = RegexpTokenizer(r'\w+').tokenize(text)

#         lemmatized = []
#         for word in tokenized:
#             word = morph.parse(word)[0].normal_form
#             lemmatized.append(word)
        
#         words_filtered = [word for word in lemmatized if word not in stop]
#         words_joined = " ".join(words_filtered)
#         return words_joined
#не стала оформлять в класс, нет необходимости, та же функция

In [38]:
def optokfil(filename): #open, tokenize, filter
        with codecs.open(filename, "r", "utf-8") as my_file:
            text = my_file.read().lower()
        tokenized = RegexpTokenizer(r'\w+').tokenize(text)

        lemmatized = []
        for word in tokenized:
            word = morph.parse(word)[0].normal_form
            lemmatized.append(word)
        
        words_filtered = [word for word in lemmatized if word not in stop]
        words_joined = " ".join(words_filtered)
        return words_joined

In [39]:
text_list = []
for file in os.scandir("6_texts"):
    text_list.append(optokfil(file.path))

In [40]:
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(l)
print ("    ант_ябл    суходол  ночной_разг господин_сф жизнь_арс поздний_ч ")
print (cosine_similarity(sparse_matrix))
# названия произведений по вертикали соответствуют горизонтали, можно ориентироваться по единице в диагонали

    ант_ябл    суходол  ночной_разг господин_сф жизнь_арс поздний_ч 
[[1.         0.58377369 0.48138843 0.47952725 0.66845403 0.47186851]
 [0.58377369 1.         0.5748729  0.54953515 0.75284478 0.50042837]
 [0.48138843 0.5748729  1.         0.47027167 0.64116593 0.42966467]
 [0.47952725 0.54953515 0.47027167 1.         0.67151551 0.43336555]
 [0.66845403 0.75284478 0.64116593 0.67151551 1.         0.65429049]
 [0.47186851 0.50042837 0.42966467 0.43336555 0.65429049 1.        ]]
